#ifndef GENERALS_CODE_LIBRARIES_SOURCE_WWVEGAS_WWLIB_RANDOM_H
#define GENERALS_CODE_LIBRARIES_SOURCE_WWVEGAS_WWLIB_RANDOM_H

// Case-preserving shim for the legacy "RANDOM.H" header.

#include "RANDOM.H"
#endif // GENERALS_CODE_LIBRARIES_SOURCE_WWVEGAS_WWLIB_RANDOM_H
