#ifndef GENERALS_CODE_LIBRARIES_SOURCE_WWVEGAS_WW3D2_DX8CAPS_H
#define GENERALS_CODE_LIBRARIES_SOURCE_WWVEGAS_WW3D2_DX8CAPS_H

// Case-preserving shim for "dx8caps.h".

#include "dx8caps.h"
#endif // GENERALS_CODE_LIBRARIES_SOURCE_WWVEGAS_WW3D2_DX8CAPS_H
