function(cnc_enable_native_warnings target_name)
    if(NOT TARGET ${target_name})
        message(FATAL_ERROR "Cannot apply native warning policy to missing target '${target_name}'")
    endif()
    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /permissive-)
        if(CNC_WARNINGS_AS_ERRORS)
            target_compile_options(${target_name} PRIVATE /WX)
        endif()
    else()
        target_compile_options(${target_name} PRIVATE
            -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion)
        if(CNC_WARNINGS_AS_ERRORS)
            target_compile_options(${target_name} PRIVATE -Werror)
        endif()
    endif()
endfunction()
