function(cnc_enable_native_warnings target_name)
    if(NOT TARGET ${target_name})
        message(FATAL_ERROR "Cannot apply native warning policy to missing target '${target_name}'")
    endif()
    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /permissive-)
        if(CNC_WARNINGS_AS_ERRORS)
            target_compile_options(${target_name} PRIVATE /WX)
        endif()
    else()
        target_compile_options(${target_name} PRIVATE
            -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion)
        if(CNC_WARNINGS_AS_ERRORS)
            target_compile_options(${target_name} PRIVATE -Werror)
        endif()
    endif()
endfunction()

function(cnc_enable_native_sanitizers target_name)
    if(NOT CNC_ENABLE_SANITIZERS)
        return()
    endif()
    if(MSVC)
        message(FATAL_ERROR "CNC_ENABLE_SANITIZERS requires a Clang/GCC generator on this platform")
    endif()
    target_compile_options(${target_name} PRIVATE
        -fsanitize=address,undefined -fno-omit-frame-pointer)
    # Static libraries do not link the sanitizer runtimes themselves.  Publish
    # the flags through the installed target so external consumers get the
    # same instrumentation when they link a sanitized package.
    target_link_options(${target_name} INTERFACE -fsanitize=address,undefined)
    get_target_property(_target_type ${target_name} TYPE)
    if(NOT _target_type STREQUAL "STATIC_LIBRARY")
        target_link_options(${target_name} PRIVATE -fsanitize=address,undefined)
    endif()
endfunction()
