if(NOT DEFINED CNC_SOURCE_DIR)
    message(FATAL_ERROR "CNC_SOURCE_DIR must point at the project source tree")
endif()
set(_roots "${CNC_SOURCE_DIR}/engine" "${CNC_SOURCE_DIR}/games" "${CNC_SOURCE_DIR}/tests")
set(_forbidden_regex "gamespy|safedisk|copy[_-]?protection|do_copy_protection")
set(_native_width_regex "(^|[^A-Za-z0-9_])(unsigned[ \\t]+long|long[ \\t]+long|unsigned[ \\t]+int)([^A-Za-z0-9_]|$)")
set(_implementation_size_regex "std::size_t")
set(_violations)
foreach(_root IN LISTS _roots)
    if(NOT EXISTS "${_root}")
        continue()
    endif()
    file(GLOB_RECURSE _files LIST_DIRECTORIES false
        "${_root}/*.c" "${_root}/*.cc" "${_root}/*.cpp" "${_root}/*.cxx"
        "${_root}/*.h" "${_root}/*.hpp" "${_root}/*.inl")
    foreach(_file IN LISTS _files)
        file(READ "${_file}" _contents)
        string(REGEX MATCH "${_forbidden_regex}" _match "${_contents}")
        if(_match)
            list(APPEND _violations "${_file}: ${_match}")
        endif()
        string(REGEX MATCH "${_native_width_regex}" _width_match "${_contents}")
        if(_width_match)
            list(APPEND _violations "${_file}: non-fixed-width type ${_width_match}")
        endif()
        string(REGEX MATCH "${_implementation_size_regex}" _size_match "${_contents}")
        if(_size_match)
            list(APPEND _violations "${_file}: use ft_size_t instead of std::size_t")
        endif()
    endforeach()
endforeach()
if(_violations)
    string(REPLACE ";" "\n" _report "${_violations}")
    message(FATAL_ERROR "Migration source policy violations found in active sources:\n${_report}")
endif()
message(STATUS "Migration source audit passed: legacy backends absent and integer widths explicit")
