if(NOT DEFINED CNC_SOURCE_DIR)
    message(FATAL_ERROR "CNC_SOURCE_DIR must point at the project source tree")
endif()
set(_roots "${CNC_SOURCE_DIR}/engine" "${CNC_SOURCE_DIR}/games" "${CNC_SOURCE_DIR}/tests")
set(_forbidden_regex "gamespy|safedisk|copy[_-]?protection|do_copy_protection")
set(_violations)
foreach(_root IN LISTS _roots)
    if(NOT EXISTS "${_root}")
        continue()
    endif()
    file(GLOB_RECURSE _files LIST_DIRECTORIES false
        "${_root}/*.c" "${_root}/*.cc" "${_root}/*.cpp" "${_root}/*.cxx"
        "${_root}/*.h" "${_root}/*.hpp" "${_root}/*.inl")
    foreach(_file IN LISTS _files)
        file(READ "${_file}" _contents)
        string(REGEX MATCH "${_forbidden_regex}" _match "${_contents}")
        if(_match)
            list(APPEND _violations "${_file}: ${_match}")
        endif()
    endforeach()
endforeach()
if(_violations)
    string(REPLACE ";" "\n" _report "${_violations}")
    message(FATAL_ERROR "Forbidden legacy dependency references found in active sources:\n${_report}")
endif()
message(STATUS "Migration source audit passed: SafeDisk/GameSpy references absent")
